export const EVENT_TYPES = Object.freeze({
    ORDER_CREATED: "ORDER_CREATED",
    ORDER_READY: "ORDER_READY",
    ORDER_CANCELLED: "ORDER_CANCELLED",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED",

    INVENTORY_UPDATED: "INVENTORY_UPDATED",

    EMAIL_SENT: "EMAIL_SENT",
    SMS_SENT: "SMS_SENT",
});